/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../BaseStation/Msg.h.
 */

public class Constants  {
    public static final short AM_SAMPLEMSG = 147;
    public static final short AM_COMMANDMSG = 148;
    public static final byte DEFAULT_INTERVAL = 100;
}
